### PR TITLE
ARM: dts: qcom: msm8226-microsoft: Add accelerometer and magnetometer for superman and dempsey

### PR DESCRIPTION
**Pull request by RayyanAnsari**
Adds the Kionix KX022-1020 accelerometer and the Asahi Kasei AK09911 magnetometer to:
 - Nokia Lumia 730 (superman)
 - Microsoft Lumia 640 (dempsey)

### CODE REVIEW

**Comment by RayyanAnsari** [comment]
Note to self: Lumia 630 (moneypenny) uses the KX022-1020 as well.

**Comment by qaz6750** [comment]
that good,but Does it work?

**Comment by qaz6750** [comment]
can I add https://github.com/LumiaARM32-Project/linux ？

**Comment by RayyanAnsari** [comment]
I'm going to push this to https://github.com/Mainline4Lumia/linux/tree/msm8x26-next

**Pull request closed without merging**
