### PR TITLE
dts:Add lumia930 initial support

### PR DESCRIPTION
**Pull request by qaz6750**
Add lumia930 initial support

### CODE REVIEW

**Comment by qaz6750** [comment]
Maybe I should use another branch, but I have no right to add it

**Comment by qaz6750** [comment]
I hope msm8974 can also get Linux support. Of course, we can https://github.com/masneyb/nexus-5-upstream For reference

**Comment by leandrofriedrich** [comment]
huh, seems like someone is doing the work i was doing too! should have opened a MR lol

**Comment by qaz6750** [comment]
> huh, seems like someone is doing the work i was doing too! should have opened a MR lol

If I can, I hope you can guide me why I can't load DTB?
75D065F2AE232D7AFCE2183B48F58F60

**Pull request closed without merging**
