### PR TITLE
Lumia 930 bringup

### PR DESCRIPTION
**Pull request by leandrofriedrich**
Wtf how do I do this someone please help I don't want my code rotting in my fork pls-

### CODE REVIEW

**Comment by halal-beef** [comment]
:trollface:

**Comment by maj113** [comment]
Goofy ahh

**Comment by halal-beef** [comment]
:trollface:

**Comment by leandrofriedrich** [comment]
Too much meme-ing jesus

**Comment by halal-beef** [comment]
NO

**Pull request closed without merging**
